# Generated by Django 5.1.6 on 2025-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='origin',
            field=models.CharField(choices=[('dubai', 'Дубайский'), ('saudi', 'Саудовский'), ('other', 'Другой')], default='other', max_length=10),
        ),
    ]
