# Generated by Django 5.1.6 on 2025-03-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_perfume_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='origin',
        ),
    ]
