# Generated by Django 5.1.6 on 2025-03-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_perfume_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.gender'),
        ),
    ]
