# Generated by Django 5.1.6 on 2025-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gender_alter_perfume_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='price',
        ),
        migrations.AddField(
            model_name='perfume',
            name='has_10ml',
            field=models.BooleanField(default=True, verbose_name='Есть 10 мл'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='has_5ml',
            field=models.BooleanField(default=True, verbose_name='Есть 5 мл'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_10ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за 10 мл'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_5ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за 5 мл'),
        ),
    ]
