# Generated by Django 5.1.6 on 2025-03-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_perfume_price_perfume_has_10ml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Объем (мл)')),
            ],
            options={
                'verbose_name': 'Объем',
                'verbose_name_plural': 'Объемы',
                'ordering': ['size'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'verbose_name': 'Парфюм', 'verbose_name_plural': 'Парфюмы'},
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='has_10ml',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='has_5ml',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='price_10ml',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='price_5ml',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='PerfumeVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='catalog.perfume', verbose_name='Парфюм')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.volume', verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Объем парфюма',
                'verbose_name_plural': 'Объемы парфюмов',
                'ordering': ['volume__size'],
                'unique_together': {('perfume', 'volume')},
            },
        ),
    ]
