# Generated by Django 5.1.7 on 2025-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_volume_alter_category_options_alter_gender_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='code',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10),
        ),
    ]
