# Generated by Django 5.1.7 on 2025-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Unisex', 'Unisex')], default='Unisex', max_length=50, verbose_name='Пол'),
        ),
    ]
