# Generated by Django 5.1.7 on 2025-03-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_gender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ноты аромата'),
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfumes/additional/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='catalog.perfume')),
            ],
            options={
                'verbose_name': 'Изображение парфюма',
                'verbose_name_plural': 'Изображения парфюмов',
                'ordering': ['order'],
            },
        ),
    ]
