# Generated by Django 5.1.7 on 2025-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_perfume_notes_perfumeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
