# Generated by Django 5.1.7 on 2025-03-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_perfume_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
    ]
