# Generated by Django 5.1.7 on 2025-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_perfume_is_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumevolume',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
